apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arnova

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - django-secret.yaml
  - postgres-deployment.yaml
  - nginx-configmap.yaml
  - django-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: arnova
  app.kubernetes.io/version: 1.0.0
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "Arnova E-Commerce Platform"
  author: "Shopify Kenya"
