---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: arnova
type: Opaque
stringData:
  postgres-user: arnova_user
  postgres-password: arnova_password
  postgres-db: arnova_db
